### ISSUE TITLE
Create a Navbar

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/VestTech#15]
### Description

For understanding of UI/UX check [here](https://www.figma.com/file/SVAiVI2jOA3fjVPcLI48wL/Untitled?node-id=0%3A1)

Make sure the page is responsive in MOBILE , TAB . DESKTOP , LAPTOP
Add screenshots for the same.

### Screenshots

![2022-06-17](https://user-images.githubusercontent.com/78967360/174227392-d3fed124-e732-458f-9584-8aef377e5e23.png)

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/VestTech/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/VestTech/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/VestTech/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-vesttech branch.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #vesttech with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #vesttech so that we can discuss the issue there together.

Cheers 🥂

**Comment by Potato-29** [comment]
Hi @ItsRoy69 I would like work on this issue and if you allow me, can you tell where's the logo for navbar?

**Comment by ItsRoy69** [comment]
Go for it

**Comment by Potato-29** [comment]
quick question, its just a plains site right now
![Screenshot (110)](https://user-images.githubusercontent.com/53327808/174342274-24e18e10-50f9-4990-9940-9481310c7ab1.png)

Where is the logo for the navbar
 is it the one named bitcoin in images folder?

**Comment by ItsRoy69** [comment]
1. Check the steps and figma file given ... For design
2. You'll get the logo there
3. You'll have to code the navbar by looking at the design

**Comment by Potato-29** [comment]
Okay got it! thanks

**Comment by Potato-29** [comment]
Hi, I've finished the navbar, Sorry I didn't understand what you meant by "lease tag me in #milan with the Screenshot of whatever you made so that we can review that there together."

**Comment by ItsRoy69** [comment]
Can you just paste the screenshots of your work ?

**Comment by Potato-29** [comment]
![Screenshot (111)](https://user-images.githubusercontent.com/53327808/174393968-8fc93719-9b43-49e5-9558-b6898803ab7c.png)
![Screenshot (112)](https://user-images.githubusercontent.com/53327808/174393976-ed469689-f272-4f74-a35a-dc26c63b357f.png)
![Screenshot (113)](https://user-images.githubusercontent.com/53327808/174393978-ae492ee1-d732-48a2-9a1b-e92ba550f0c6.png)
![Screenshot (114)](https://user-images.githubusercontent.com/53327808/174394000-3eff5fd6-262c-4059-956c-8209467a7f7b.png)

**Comment by ItsRoy69** [comment]
Looks good to me. Make a PR

**Comment by Potato-29** [comment]
Hi, I can't make a PR, It says "Permission to ItsRoy69/VestTech.git denied to Potato-29"
