### ISSUE TITLE
Create a banner

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/VestTech#16]
### Description

For understanding of UI/UX check [here](https://www.figma.com/file/SVAiVI2jOA3fjVPcLI48wL/Untitled?node-id=0%3A1)

Make sure the page is responsive in MOBILE , TAB . DESKTOP , LAPTOP
Add screenshots for the same.

### Screenshots

![2022-06-17 (1)](https://user-images.githubusercontent.com/78967360/174227687-9f5385f5-3a07-4558-9c87-1709f575a5d2.png)

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/VestTech/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/VestTech/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/VestTech/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-vesttech branch.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #vesttech so that we can discuss the issue there together.

Cheers 🥂

**Comment by Potato-29** [comment]
Hi @ItsRoy69, Can I work on this too? :)

**Comment by ItsRoy69** [comment]
go for it
