### ISSUE TITLE
Create About section

### ISSUE THREAD

**Issue by ItsRoy69** [ItsRoy69/VestTech#17]
### Description

For understanding of UI/UX check [here](https://www.figma.com/file/SVAiVI2jOA3fjVPcLI48wL/Untitled?node-id=0%3A1)

About section should be done in the Home.jsx file . You don't need to make another file to add the "About" section.

Code should be clean and section should be divided with comments so that viewers can differentiate the code. 

Make sure the page is responsive in MOBILE , TAB . DESKTOP , LAPTOP
Add screenshots for the same.

### Screenshots

![2022-06-17 (2)](https://user-images.githubusercontent.com/78967360/174227934-93cd03cf-9b37-4812-b24d-f3c4bd0912fb.png)

### Additional information

Guidelines ⚠
I will follow the [Setup Guidelines](https://github.com/ItsRoy69/VestTech/blob/main/rules/Setup.md)
I will follow the [Contributing Guidelines](https://github.com/ItsRoy69/VestTech/blob/main/CONTRIBUTING.md)
I will follow the [Code of Conduct](https://github.com/ItsRoy69/VestTech/blob/main/CODE_OF_CONDUCT.md)

<hr>

Notice ⛔
You will make PRs only to itsroy69-main branch.
Commit message / PR title--> fix: bla bla bla

Please make sure in the .css files you are making/using , the styles should be applied to Unique Class names

<hr>

Completed / Doubts ? 🚀

Once you are done with the code , please tag me in #milan with the Screenshot of whatever you made so that we can review that there together.
If you have any doubts, queries please tag me in #vesttech so that we can discuss the issue there together.

Cheers 🥂

**Comment by Imagine96** [comment]
hi, you put that is allowed to go font google for the font but that font is not available there (the font in Figma is Microsoft YaHei UI) . Can you provide a link to the font or should i use other one?

**Comment by ItsRoy69** [comment]
You can use any font you want.

**Comment by KiranBendkoli1** [comment]
Hi @ItsRoy69 I have created about section 
as I am new to open source I have directly cloned and updated code
I will fork and make pull request tommorow if this output is fine and let me know if there's some changes


![Screenshot from 2022-06-18 00-59-34](https://user-images.githubusercontent.com/72014320/174391594-5fad5664-a31a-4899-a1e4-c970f14c8af4.png)
![Screenshot from 2022-06-18 00-59-42](https://user-images.githubusercontent.com/72014320/174391599-954c3667-aca0-40a2-9d3a-321ff92fbb78.png)
![Screenshot from 2022-06-18 01-00-00](https://user-images.githubusercontent.com/72014320/174391605-c9a3a5a1-c9d6-4331-92e5-2c9275153652.png)

**Comment by ItsRoy69** [comment]
Since @Imagine96 didn't ask for assigning him so @KiranBendkoli1 you can fork and push it
This looks cool to me.
